name: CI/CD FastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (optional)
      run: echo "Tests passed!"

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}        # e.g., 20.127.201.103
        username: ${{ secrets.SERVER_USER }}  # e.g., dpd
        key: ${{ secrets.SERVER_SSH_KEY }}    # private SSH key (must be added in GitHub Secrets)
        port: ${{ secrets.SERVER_PORT }}      # e.g., 22
        timeout: 60s                          # Increase timeout if needed
        script: |
          # Go to project directory
          cd /home/dpd/Devora_API.0

          # Activate virtual environment
          source venv/bin/activate

          # Pull latest code
          git pull origin main

          # Install dependencies
          pip install -r requirements.txt

          # Restart FastAPI app via PM2
          pm2 restart Devora_API || pm2 start venv/bin/uvicorn --name Devora_API --interpreter python3 -- api:app --host 0.0.0.0 --port 8000
          pm2 save

          # Restart Nginx
          sudo systemctl restart nginx
